name: Build and Run JavaFX App

on:
  push:
    branches:
      - main
      - release
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository # Linux
            C:\Users\runneradmin\.m2\repository # Windows
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean package -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}

      - name: Run the application
        run: |
          mvn javafx:run -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}
