name: Build and Run on Multiple OS

on:
  push:
    branches:
      - main
      - release
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository # Linux
            C:\Users\runneradmin\.m2\repository # Windows
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean package -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}

      - name: Ensure no previous Xvfb instances
        if: runner.os == 'Linux'
        run: |
          sudo pkill Xvfb || true

      # Use Xvfb to simulate a display on Linux
      - name: Start Xvfb and run tests on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xauth x11-utils
          Xvfb :99 -screen 0 1920x1080x24 -ac &
          sleep 5  # Give Xvfb some time to start
          cat xvfb.log  # Check the log for Xvfb errors
          export DISPLAY=:99
          xvfb-run mvn javafx:run -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}

      # Run the application on Windows
      - name: Run the application on Windows
        if: runner.os == 'Windows'
        run: |
          mvn javafx:run -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}
