name: Build and Run on Multiple OS

on:
  push:
    branches:
      - main
      - release
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository # Linux
            C:\Users\runneradmin\.m2\repository # Windows
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean package -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}

      - name: Setup Xvfb
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1

      - name: Run the application on Linux
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:99
          mvn javafx:run -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}

      - name: Run the application on Windows
        if: runner.os == 'Windows'
        run: |
          mvn javafx:run -Drevision=${{ github.sha }} -Dbranch=${{ github.ref_name }}